---
title: "Data Related Stuff"
author: "Dean Gladish"
date: "July 28, 2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```


This R Markdown is just an inquiry into the statistics and facts surrounding data breaches in the United States.  Unlike the more traditional form of just summarizing the laws I wanted to create a document which would also give some helpful statistics which could be updated immediately.  

## Let's Begin


\ \ \ \ \ \ \ This shiny app is intended to do just that.  

```{r Load and wrangle data, message = FALSE, warning = FALSE, echo = FALSE}
library(readr)

statesData <- read_csv("statesSimplified.csv")


# Remove unneeded columns
statesData <- subset(statesData, select = c(1:13))

# Replace all NA values with the integer 0
statesData[is.na(statesData)] <- 0


library(ggplot2)




ggplot(data = statesData, mapping = aes(x = modifiedLawsin2018or2019, fill = modifiedLawsin2018or2019)) + 
  geom_bar() + 
  labs(title = "Proportion of States", x = "", y = "Number of States") + 
  theme(panel.background = element_blank()) + 
  geom_hline(yintercept = seq(0, 50, by = 10), col = "white", lwd = 1) + 
  theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
  geom_text(aes(label=..count..), stat="count", position = position_stack(), vjust = 1.5, color = "white") + 
  theme(legend.position = "none") + 
  scale_x_discrete(limit = c("FALSE", "TRUE"),
                     labels = c("Did not modify laws 2018-2019", "Modified laws 2018-2019"))
  



```

`r statesData[1,]`

```{r Shiny App for Data Breach Laws, echo = FALSE}
library(shiny)

axis_vars <- c(
  "Modified its Laws in 2018-2019" = "modifiedLawsin2018or2019", 
  "With DOB as PI" = "hasDOBasPI", 
  "With Online (vs. financial) account as PI" = "hasOnlineAccountsasPI", 
  "\"access\" vs. acquisition" = "requiresAcquisitionNotJustAccess", 
  "Harm analysis allowed or not" = "harmAnalysisAllowed", 
  "Government Involvement or not" = "governmentInvolvementRequired", 
  "Reporting threshold: number of individuals to notify Attorney General" = "thresholdNotifyAG",
  "Reporting threshold: number of individuals to notify consumer reporting agency" = "thresholdNotifyCRA", 
  "Time Frame within which to notify" = "timeFrame", 
  "Requirement for \"service provider\" to report to data owner immediately or not" = "serviceProvidersNotifyImmediately", 
  "Harm analysis required or not" = "harmAnalysisRequired", 
  "With Financial (vs. online) account as PI" = "financialAccountInformationisPI"
)





library(stringr)

statesData$placeHolderColumn <- c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)

sidebarLayout(
    sidebarPanel(
      helpText("Filter States by the Following Criteria."),
      
      selectInput("var", 
                  label = "Choose a variable to display",
                  choices = c("all states" = toString(which(statesData$placeHolderColumn)),
                    "modifiedLawsin2018or2019" = toString(which(statesData$modifiedLawsin2018or2019)), 
                              "hasDOBasPI" = toString(which(statesData$hasDOBasPI))),
                  selected = "Percent White"),
      
      sliderInput("range", 
                  label = "Range of Attorney General Notification Thresholds:",
                  min = 0, max = 1000, value = c(0, 1000))
    ),
    
    mainPanel(
      textOutput("selected_var"),
      textOutput("min_max")
    )
  )

renderUI({
  HTML(str_replace_all(toString(
    paste(toString(statesData[
      
      intersect(
      
      as.integer(unlist(strsplit(input$var, split = ", "))), 
      
      intersect(which(statesData$thresholdNotifyAG >= input$range[1]), which(statesData$thresholdNotifyAG <= input$range[2]))
      
      )
      
      
      ,]$State))
    )
    , ", ", "<br/>"))
})



#-------------------------------------------------------------------------------------------




axis_vars_graph2 <- c(
  "Reporting threshold: number of individuals to notify Attorney General" = "thresholdNotifyAG",
  "Reporting threshold: number of individuals to notify consumer reporting agency" = "thresholdNotifyCRA", 
  "Time Frame within which to notify" = "timeFrame"
)
inputPanel(
  
  selectInput("yvar", label = "Y-axis variable", choices = axis_vars_graph2, 
              selected = "Cost_of_Revenue")
)

# This part is not the best way to code this.  How else can this be done (for example, by using aes_string instead of aes)?  
renderPlot({
  if (input$yvar == "thresholdNotifyAG") {
    ggplot(statesData) + 
  geom_bar(mapping = aes(x = reorder(State, thresholdNotifyAG), y = thresholdNotifyAG), stat = "identity") + 
  xlab("State") + 
  theme(panel.background = element_blank()) + 
  theme(axis.ticks = element_blank()) + 
  labs(title = "States and Threshold", y = "To Notify Attorney General") + 
  geom_hline(yintercept = seq(0, 1000, by = 250), colour = "gray", size = 1, linetype = 21) + 
  coord_flip() + 
  theme(axis.text.y = element_text(size = 7))
  }
  
  else if (input$yvar == "thresholdNotifyCRA") {
    ggplot(statesData) + 
  geom_bar(mapping = aes(x = reorder(State, thresholdNotifyCRA), y = thresholdNotifyCRA), stat = "identity") + 
  xlab("State") + 
  theme(panel.background = element_blank()) + 
  theme(axis.ticks = element_blank()) + 
  labs(title = "States and Threshold", y = "To Notify Consumer Reporting Agencies") + 
  geom_hline(yintercept = seq(0, 10000, by = 1000), colour = "gray", size = 1, linetype = 21) + 
  coord_flip() + 
  theme(axis.text.y = element_text(size = 7))
  }
  
  else if (input$yvar == "timeFrame") {
    ggplot(statesData) + 
  geom_bar(mapping = aes(x = reorder(State, timeFrame), y = timeFrame), stat = "identity") + 
  xlab("State") + 
  theme(panel.background = element_blank()) + 
  theme(axis.ticks = element_blank()) + 
  labs(title = "States and Threshold", y = "How Long to Disclose") + 
  geom_hline(yintercept = seq(0, 100, by = 10), colour = "gray", size = 1, linetype = 21) + 
  coord_flip() + 
  theme(axis.text.y = element_text(size = 7))
  }
})
```












